### ISSUE TITLE
Feature request: Add additional TO: or CC: email addresses to contacts

### ISSUE THREAD

**Issue by mburnicki** [thundernest/k-9#1120]
In the current version I can only click on the _FROM:_ email or name to get the option to add it to my contacts list. If I get an email starting a conversation with some additional _TO:_ or _CC:_ recipients which are not yet stored in my contacts it would be great if I could add them to my address book as easily as the sender of the email, just by clicking on the names or email addresses.

**Comment by AurelCharp** [comment]
Hi,
I added a solution to add a contact by clicking on the email address on the _TO:_ like it's in the current version on the _FROM:_, but I don't know how to do it for the _CC:_. In the _CC:_ view, I can just recover a string with all _CC:_ recipients but not just the email address that I clicked.
Do you have an idea about this ?
Do I have to do a pull request with the _TO:_ solution or must I wait for the complete solution with the _CC:_ ?

**Comment by philipwhiuk** [comment]
@AurelCharp I'd welcome a PR that fixes it for To. We can always fix CC later.

**Comment by cketti** [comment]
Closing this in favor of #6181.
