### ISSUE TITLE
Remove drafts instead of moving them to the Trash on sending

### ISSUE THREAD

**Issue by philipwhiuk** [thundernest/k-9#2261]
### Expected behavior
Sending a message that was stored in the Drafts folder should remove the Draft

### Actual behavior
The draft is moved to the Trash folder.

### Developer notes

See #1467

**Comment by philipwhiuk** [comment]
I don't think we ever want to move a draft to the trash folder, so this is probably much more straightforward than it was made out to be.

**Comment by asmith15** [comment]
I don't know if it's just me but I feel like I end up with a half-written message in my trash/deleted folder every time I compose a message using K9.

Is there any purpose in doing that? I definitely want a drafts folder, but I see no reason to move any drafts to the trash, and I can't even image a reason one might want the draft in the trash after the final message has been successfully sent.

**Comment by philipwhiuk** [comment]
I think it was just written wrong originally.

I've actually rewoke my Android from the dead recently but I'm still snowed under with other projects.

**Comment by asmith15** [comment]
Excuse my ignorance, is it a simple type of fix? If it is - I can try to help. I don't have any spare time either but I could dedicate a few hours to this.

**Comment by schlagi123** [comment]
@cketti I want to work in this issue, But I have one question on that:

How should be the behavior, if I delete a draft? Should it move to the deletion directory or should it delete compleatly too?

**Comment by cketti** [comment]
@schlagi123: Nice :+1: 

I think discarding or deleting a draft should still move it to the trash folder.
