### ISSUE TITLE
localization issues

### ISSUE THREAD

**Issue by akerbeltz** [thundernest/k-9#2649]
Hi. I've just about completed the localization into gd-GB and I've noticed some l10n issues that probably affect other locales too.

dialog_confirm_delete_messages 
dialog_confirm_spam_message
settings_import_accounts
are problematic for translation because English has
Do you really want to delete this message?
Do you really want to delete <xliff:g id="message_count"> messages?
(or in one case it has the digit 1 as a number in the en-US string)
but Transifex throws a fit when I try to add the message_count placeholder to our ONE (we have 4 plural forms, ONE, TWO, FEW, OTHER) string because the source does not have the placeholder. I cannot even just say "ok, I'll ignore what happens with 11 (ONE covers 1 and 11)" because somehow Transifex links English ONE to Gaelic ONE and TWO i.e. I cannot translate TWO with the placeholder either. Transifex just refuses to save the message.
The quickest solution would be to just put the placeholder into en-US ONE as well.

remote_search_downloading 
remote_search_downloading_limited 
use number placeholders but there must be an error because Transifex does not offer the plural fields for translation.

pull_to_refresh_remote_search_from_local_search_pull 
pull_to_refresh_remote_search_from_local_search_release 
are a little opaque and would benefit from a comment as to whether pull/release is a physical action on my device or whether you mean "perform a pull from a repo" / "release to repo" (I suspect the latter but really not sure)

copy_address_to_clipboard 
settings_import_server_passwords 
settings_import_setting_passwords 
seem to be set up for pluralization but do not have number placeholders and I'm not sure they are meant to be pluralized at all.

**Comment by akerbeltz** [comment]
Ah I forgot one. There is locale duplication which is not a good use of localizer time plus it eats into the Transifex data allowance:
Galician
Galician (Spain)
Malayalam (no translators)
Malayalam (India)

**Comment by philipwhiuk** [comment]
* pull_to_refresh_remote_search_from_local_search_pull 
* pull_to_refresh_remote_search_from_local_search_release

This is swipe down action assistance text - i.e. the former.

* copy_address_to_clipboard

Is pluralised with no placeholder to allow for 'address' or 'addresses'. In English it is better grammar to be able to depluralise some words.

> but Transifex throws a fit when I try to add the message_count placeholder to our ONE (we have 4 plural forms, ONE, TWO, FEW, OTHER) string because the source does not have the placeholder. I cannot even just say "ok, I'll ignore what happens with 11 (ONE covers 1 and 11)" because somehow Transifex links English ONE to Gaelic ONE and TWO i.e. I cannot translate TWO with the placeholder either. Transifex just refuses to save the message.

:( 

* remote_search_downloading
* remote_search_downloading_limited

I'll file a PR to make these plurals

**Comment by akerbeltz** [comment]
Thank you so far. I have added two comments on Transifex for 

- pull_to_refresh_remote_search_from_local_search_pull
- pull_to_refresh_remote_search_from_local_search_release

so it's clearer to the other localizers in future

**Comment by akerbeltz** [comment]
I can confirm the two remote_search strings have been fixed but these

dialog_confirm_delete_messages
dialog_confirm_spam_message
settings_import_accounts

are still as they were

**Comment by cketti** [comment]
Shouldn't this bug be fixed by Transifex rather than us having to work around it?

**Comment by comradekingu** [comment]
@akerbeltz 
With Weblate now in use, there is a list of cases to use per language for pluralized strings.
https://hosted.weblate.org/translate/tb-android/app-strings/gl/?checksum=4e98118db056b918 is the string you mentioned.
Weblate also has a list of proper locales, and should complain about duplicated ones.

Issue can be closed?
