### ISSUE TITLE
media query support

### ISSUE THREAD

**Issue by Djfe** [thundernest/k-9#3117]
Hi,
It looks to me like k9 doesn't support media queries.
I know, it's far from required or standard, but since this is a mobile e-mail client, I think media queries would definitely be a beneficial feature.

It would be very cool if you could add support for them in the future :)

At least ebay uses them. (to restructure layout, add padding to containers and show different images for the mobile version (images being text))

I attached an e-mail by them as an example
(I know it's ugly code; I wanted to projectile vomit when taking a closer look. 3-layered tables for layout and images for text formatting. A yahoo fix and 72kb of size; probably not new to you though ^^)
[ebay_email.zip](https://github.com/k9mail/k-9/files/1649573/ebay.zip)

Though, if you add support, then you should think about different the different displays (low/high res, different aspect ratios etc.) and in each these cases what width e-mails should be displayed at. (in-case you haven't already, obviously)

Regards,
Djfe

PS: it could also be, that K9 doesn't support css attribute selectors, yet. (or some other feature, that the example requires; I would be glad if you could take a closer look :) )

EDIT:
My smartphone has a resolution of 1920x1080, so I'm not sure, whether the media rules in the file even apply. What viewport width would k9 use on my device?

**Comment by Djfe** [comment]
I "measured" your viewport width by comparing another e-mail in k9 with thunderbird and measuring the px value that fits. (by adjusting width until it looked the same despite automatic line-breaks in text)
I'm fairly certain, that the viewport of k9 is around 440px wide on my full hd device (around 2.45 px ratio)
therefore this media query should trigger, but it doesn't:
```
@media only screen and (max-width: 479px) {
```
I know that, because k9 shows images meant for desktop instead of the mobiles ones (with smaller width)
The switch for these class to show/hide happens in the query

**Comment by cketti** [comment]
We insert `<meta name="viewport" content="width=device-width"/>`. Could this be the problem?

**Comment by Djfe** [comment]
well 600-700px width seems to be regarded as desktop (according to some people on the internet, that was the e-mail width in outlook on a 1024x768 screen, and it stayed the default since then)
and 460px (or something like that) is mobile high res
some do a version for 300px

https://litmus.com/community/discussions/1142-email-maximum-width-still-600px

you could do 640px for tablets/landscape mode
320px for smartphones (exactly half the width)
and maybe an additional step: 460px for high-res smartphones (seems to be a good value)

good read:
https://blog.chamaileon.io/limitations-of-html-email-design-email-width-and-size/
you should do this:
https://www.email-standards.org/
(some stuff on their website sadly returns 404s, but I received the acid test e-mail despite a 404, so you should be able to take a look at it)

It would be nice to see, how e-mails look with:
```
<meta name="viewport" content="width=450, initial-scale=2.0">
```
If e-mails wider than 450px would get a scrollbar because of that, then maybe just device-width + initial-scale 2.0
or maybe even scale 3.0

I also just came across:
```
<meta name="viewport" content="target-densitydpi=device-dpi">
```
Possible values for target-densitydpi are device-dpi, high-dpi, medium-dpi, low-dpi.

The problem is: there are many people trying to create e-mails and fight around clients, but barely any ressources on client development. (at least my quick google search didn't reveal more) 

are there other ways to tell the webview to use 460px as the device-width but scale to max-width of the content, that don't revolve around a meta-tag? Because the meta-tag implies, that the e-mail writer/html creater knows, how it has to look. But you as the dev don't know that, since there are many different mails out there.
(the webview takes the meta tag explicitly even if the content is wider (it has to be width x, if they say so), probably, which wouldn't help)

Just a way, so that the media queries are interpreted correctly (mobile px range(s)), the rest doesn't matter so much.

**Comment by Djfe** [comment]
apparently the meta tag is actually the way to go, but it should help, if setLoadWithOverviewMode and setUseWideViewPort are both set to true and width is 460px.
In that case the webview should show the full width, if it's wider than 460px, but if the layout supports it, stay at 460px. (for tablets/layout I would still like 640px/650px more, I think; I don't know whether it's still relevant to support screens smaller than 460px; my first smartphone had 854x480, but afaik there were smaller resolutions, so maybe you want to adjust the value to device-width for these as an exception)

https://developer.android.com/reference/android/webkit/WebSettings.html#setLoadWithOverviewMode(boolean)
https://developer.android.com/reference/android/webkit/WebSettings.html#setUseWideViewPort(boolean)

**Comment by Djfe** [comment]
I'm wondering whether setting WebSettings.LayoutAlgorithm to TEXT_AUTOSIZING will improve the way e-mails look (or not)
https://developer.android.com/reference/android/webkit/WebSettings.LayoutAlgorithm.html
