### ISSUE TITLE
No notification when SMTP server rejects outgoing message

### ISSUE THREAD

**Issue by aarantala** [thundernest/k-9#3766]
When trying to send a message fails because the SMTP server rejects the message user is not notified in any way. Instead, user is just left wondering why the message just sits in Outbox in spite of trying 'Send messages'.

### Expected behavior
When the SMTP server rejects outgoing message user is notified, preferrably with some indication why the message was rejected, e.g. 'SMTP server complains that the message is too large or has too many recipients'.

### Actual behavior
User gets no notification, message is just stuck in Outbox, and when user goes there and launches 'Send messages' nothing visible happens and the message just keeps on sitting in the Outbox.

### Steps to reproduce
1.Ensure that the (test) SMTP server will reject the outgoing message, e.g. by setting some limit ridiculously low (like maximum number of recipients = 1)
2.Create a message that will be rejected, like two or more recipients when the SMTP server is set to accept only messages with one recipient.
3.Try sending the message, go to Outbox and try 'Send messages' a random number of times and wonder what is happening.

### Environment
K-9 Mail version:5.600

Android version:8.0.0

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by cketti** [comment]
K-9 Mail now creates notifications for send failures.
