### ISSUE TITLE
To/CC me indicator should always be displayed in front of sender name in message list

### ISSUE THREAD

**Issue by cketti** [thundernest/k-9#4152]
Right now we prefix the second line in message list items with `»` when one of the user's email addresses is found in the `To` header. When one of the user's addresses was found in the `Cc` header the line is prefixed with `›`.

I want to change this so the indicator is always displayed in front of the sender name, i.e. in the first line when the setting "Correspondent above subject" is checked.

**Comment by basil-conto** [comment]
[ Sorry for the noise here - my other searches came up dry. ]

Does this feature (the inclusion of `›` and `»` indicators) still exist in the current version of K-9 / Thunderbird?  If so, could you please point me towards where it's configured/implemented?  If not, is there interest in re-adding it?

Thanks!
