### ISSUE TITLE
RFC1342-encoded References not handled gracefully

### ISSUE THREAD

**Issue by mhchem** [thundernest/k-9#4228]
If the References header becomes long, ~~K-9~~ RFC1342-encodes them into the following. Here is an example of what K-9 sends (with personal data x'ed):

    References: =?us-ascii?Q?<001001d58d84$e6201780$b2604680$=3D=3Dxxxxxxxxxxx.com@xxxx.d?= =?us-ascii?Q?e>_<xxxxxxx-3126fd9b-6e51-41d8-a1e1-4ff12fb9d018-15722663862?= =?us-ascii?Q?71=3D=3D3c-xxx-xxxxx-xx02@xxxx.de>_<E9A9DAD9-16AE-4C38-ADCB-?= =?us-ascii?Q?8435CB2CBFBA=3D=3Dxxxxxxxxxxxx.de@xxxx.de>?= <001601d58d9e$850f4fa0$8f2deee0$==xxxxxxxxxxx.com@xxxx.de>

Firstly, I don't see why References need to be RFC1342-encoded at all.

Secondly, folding could be applied to limit the line length.

Thirdly, if such a mail is received by K-9, it is not recognized as belonging to the same thread. I assume K-9 does not properly decode ~~its own~~ RFC1342 encoding.

K-9 Mail 5.600, Android

**Comment by mhchem** [comment]
Addendum: When double-checking with another client, I realized that K-9's "Show headers" does not show the original header, but decodes RFC1342 first. So, it seems that K-9 is not introducing the encoding. Nevertheless, it does not handle it gracefully.

**Comment by cketti** [comment]
This should no longer be an issue in recent versions of K-9 Mail.
