### ISSUE TITLE
Add a way to distinguish the email address if the contact name is displayed

### ISSUE THREAD

**Issue by Massedil** [thundernest/k-9#4402]
I have read #1119 but I think some points explained here are different.

I have multiple e-mails addresses for some contacts (multiple emails for "Home" type and multiple emails for "Works" type).

1. In a received message, I can't easily see what is the real email for the sender and for the recipient.

Expected :
- Display in a smaller font size the email address just under the contact name
- Or, at least, touching the contact name display the email address
- Or, at least, show in the long press copy toast the complete email address

2. In a composition box in the "To" field, I can't see the email address after having selected it.

Here it is less problematical because it is possible to touch the email to see which one is selected.

Expected :
- Display in a smaller font size the email address just under the contact name

3. When sharing a text or a file from another app, 2 contacts are now suggested.

For me, it is always myself for the 2 contacts.

a. How the selected contact selection works ?
b. It is impossible to see which email will be used because the 2 thumbnail are identical (the same text and the same image is displayed for the 2 contacts) .

Expected :
- First line of the suggested contact is for the name
- Second line of the suggested contact is for the email

**Comment by BrettGitto** [comment]
Using version 5.800, I too would like to see both the corresponent's name as well as email address, displayed together in the message view, as @Massedil explained previously.

"Quoting"
In a received message, I can't easily see what is the real email for the sender and for the recipient.
Expected :

Display in a smaller font size the email address just under the contact name
Or, at least, touching the contact name display the email address
Or, at least, show in the long press copy toast the complete email address

**Comment by valerio-bozzolan** [comment]
I think this may be partially related to #1119 that seems it was implemented yesterday
