### ISSUE TITLE
Speed up contact name lookup in message list

### ISSUE THREAD

**Issue by elhennig** [thundernest/k-9#4579]
### Expected behavior
k-9 should open the inbox message list on startup immediately

### Actual behavior
Starting k-9 the message list display needs 5-10 secs to open a list of 500 messages from an IMAP account. With the productive version from the playstore (I guess this is 5.600) the list was displayed instantly.

### Steps to reproduce
1. Start k-9 opening the message list as main page

### Environment
K-9 Mail version: 5.705

Android version: 9 (LOS based)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
03-03 11:46:04.200  1432 15638 I ActivityManager: START u0 {flg=0x34000000 cmp=com.fsck.k9/.activity.MessageList (has extras)} from uid 10461
03-03 11:47:33.500  1432  3153 I ActivityManager: START u0 {cmp=com.fsck.k9/.ui.settings.SettingsActivity} from uid 10461
03-03 11:47:34.633  1432  9716 I ActivityManager: START u0 {cmp=com.fsck.k9/.ui.settings.general.GeneralSettingsActivity (has extras)} from uid 10461
03-03 11:47:35.863 13308 13308 I chatty  : uid=10461(com.fsck.k9) identical 4 lines
03-03 11:47:37.815   867  2246 D SurfaceFlinger: duplicate layer name: changing com.fsck.k9/com.fsck.k9.ui.settings.general.GeneralSettingsActivity to com.fsck.k9/com.fsck.k9.ui.settings.general.GeneralSettingsActivity#1
03-03 11:47:40.518   867  2246 W SurfaceFlinger: Attempting to set client state on removed layer: com.fsck.k9/com.fsck.k9.ui.settings.general.GeneralSettingsActivity#1
03-03 11:47:40.519   867  2246 W SurfaceFlinger: Attempting to destroy on removed layer: com.fsck.k9/com.fsck.k9.ui.settings.general.GeneralSettingsActivity#1
03-03 11:47:57.723   867  2246 D SurfaceFlinger: duplicate layer name: changing com.fsck.k9/com.fsck.k9.ui.settings.general.GeneralSettingsActivity to com.fsck.k9/com.fsck.k9.ui.settings.general.GeneralSettingsActivity#1
03-03 11:48:00.089   867  2246 W SurfaceFlinger: Attempting to set client state on removed layer: com.fsck.k9/com.fsck.k9.ui.settings.general.GeneralSettingsActivity#1
03-03 11:48:00.089   867  2246 W SurfaceFlinger: Attempting to destroy on removed layer: com.fsck.k9/com.fsck.k9.ui.settings.general.GeneralSettingsActivity#1
03-03 11:48:10.848  1432 11137 I ActivityManager: START u0 {act=android.intent.action.VIEW flg=0x14000000 cmp=com.fsck.k9/.activity.FolderList bnds=[1221,450][1221,450] (has extras)} from uid 10182
03-03 11:48:11.121  1432  1445 I ActivityManager: Displayed com.fsck.k9/.activity.FolderList: +262ms
03-03 11:48:11.215   867   962 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.fsck.k9#0
03-03 11:48:11.215   867   962 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.fsck.k9#0
03-03 11:48:23.432  1432  3446 I ActivityManager: START u0 {cmp=com.fsck.k9/.ui.settings.SettingsActivity} from uid 10461
03-03 11:48:24.822  1432 11137 I ActivityManager: START u0 {cmp=com.fsck.k9/.ui.settings.general.GeneralSettingsActivity (has extras)} from uid 10461
03-03 11:48:43.910  1432  7860 I ActivityManager: START u0 {act=android.intent.action.VIEW flg=0x14000000 cmp=com.fsck.k9/.activity.FolderList bnds=[1240,369][1240,369] (has extras)} from uid 10182
03-03 11:48:44.271   867  2247 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.fsck.k9#0
03-03 11:48:50.022 13308 13318 I com.fsck.k9: Background concurrent copying GC freed 139945(6MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 8MB/17MB, paused 78us total 142.445ms
03-03 11:48:53.404  1432  1448 I ActivityManager: Start proc 19358:com.android.webview:sandboxed_process0/u0i223 for webview_service com.fsck.k9/org.chromium.content.app.SandboxedProcessService0
03-03 11:49:04.283   867   966 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{793020 token=Token{2950323 ActivityRecord{96e0452 u0 com.fsck.k9/.activity.FolderList t4538}}}#0
03-03 11:49:44.188  1432  5430 I ActivityManager: START u0 {act=android.intent.action.VIEW flg=0x14000000 cmp=com.fsck.k9/.activity.FolderList bnds=[1072,406][1072,406] (has extras)} from uid 10182
03-03 11:49:44.597   867   962 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.fsck.k9#0
03-03 11:49:44.597   867   962 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.fsck.k9#0
03-03 11:52:58.316   867  2557 W SurfaceFlinger: Attempting to set client state on removed layer: com.fsck.k9/com.fsck.k9.activity.FolderList#0
03-03 11:52:58.317   867  2557 W SurfaceFlinger: Attempting to destroy on removed layer: com.fsck.k9/com.fsck.k9.activity.FolderList#0
03-03 11:52:58.868  1432  7193 I ActivityManager: START u0 {act=android.intent.action.VIEW flg=0x14000000 cmp=com.fsck.k9/.activity.FolderList bnds=[495,1552][495,1552] (has extras)} from uid 10182
03-03 11:52:59.244   867  2247 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.fsck.k9#0
03-03 11:52:59.245   867  2247 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.fsck.k9#0
03-03 11:53:54.812  1432  5711 I ActivityManager: START u0 {cmp=com.fsck.k9/.ui.settings.SettingsActivity} from uid 10461
03-03 11:54:12.458   867   966 W SurfaceFlinger: Attempting to set client state on removed layer: com.fsck.k9/com.fsck.k9.ui.settings.SettingsActivity#0
03-03 11:54:12.458   867   966 W SurfaceFlinger: Attempting to destroy on removed layer: com.fsck.k9/com.fsck.k9.ui.settings.SettingsActivity#0
03-03 11:56:15.309  1432 11137 I ActivityManager: START u0 {act=android.intent.action.VIEW flg=0x14000000 cmp=com.fsck.k9/.activity.FolderList bnds=[650,1448][650,1448] (has extras)} from uid 10182
03-03 11:56:15.983  1432  1445 I ActivityManager: Displayed com.fsck.k9/.activity.FolderList: +656ms
03-03 11:56:16.069   867  2247 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.fsck.k9#0
03-03 11:56:16.069   867  2247 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.fsck.k9#0
03-03 11:56:17.863 13308 13318 I com.fsck.k9: Background concurrent copying GC freed 61810(3MB) AllocSpace objects, 0(0B) LOS objects, 50% free, 10MB/20MB, paused 459us total 107.113ms
03-03 11:56:51.543   867   962 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{26855a0 token=Token{6db4ea3 ActivityRecord{ff84dd2 u0 com.fsck.k9/.activity.FolderList t4539}}}#0
03-03 11:56:52.372  1432  3446 I ActivityManager: START u0 {act=android.intent.action.VIEW flg=0x14000000 cmp=com.fsck.k9/.activity.FolderList bnds=[881,1377][881,1377] (has extras)} from uid 10182
03-03 11:56:52.606  1432  1445 I ActivityManager: Displayed com.fsck.k9/.activity.FolderList: +215ms
03-03 11:56:52.683   867  2247 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.fsck.k9#0
03-03 11:56:52.683   867  2247 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.fsck.k9#0

**Comment by cketti** [comment]
Is 'General settings > Display > Show contact names' enabled? This will fetch the contact names from the system's contact database, which has been very slow for some users in the past.

**Comment by elhennig** [comment]
Yes, that improves the performance significantly. Strange enough this was working without problems with 5.600.

**Comment by cketti** [comment]
Not really. 5.600 fetches the contact names on demand, before displaying an item in the message list. Depending on your screen size and display settings that's around 10 queries to the contacts database before the initial list can be displayed. That's probably quite a bit faster than 500 queries.
But it leads to stutters when fast-scrolling the list because new list items can't be drawn before the query for the contact name has been completed.

**Comment by elhennig** [comment]
SO maybe 5.600 had the contacts in the cache (?), When I opened the list in the 5.600 version it was there instantly. maybe scrolling was a bit more laggy, but it did not bother me. 
The list was 500 messages. After getting the beta version from the playstore the opening of the app with the 500 messages list was slow. (it was the very same list actually). Anyway I prefer to have the known contacts marked in a different color and if it takes a bit longer I can live with that. 
However if you can manage to improve the performance in the next version I'd be more than happy.

**Comment by cketti** [comment]
Optimizing this is not a priority and is unlikely to happen before the next stable version is released.

**Comment by elhennig** [comment]
OK, thanks anyways. 
For me a workaround is to limit the number of messages to 250 (instead of 500).

**Comment by elhennig** [comment]
With 5.727 the initial display of the mail list became really slow, even if the number of messages is limited further. Any idea where this comes from or how to improve this?

**Comment by elhennig** [comment]
Currently I am using version 6.501 and today I tried again how long the opening of the message list initially takes. Even if this issue does not seem to have been worked on, the message list on opening the app is fast as before this issue was opened by me.
