### ISSUE TITLE
UI - Clean up header in messages

### ISSUE THREAD

**Issue by Donkey-Doug** [thundernest/k-9#4802]
The reason for this suggestion is that the header take up so much space while displaying very few info.

Several suggestions:
- I only use one account, so the account color does not make sense for me. It is always shown in the header of every message.
- The star (favorite) and reply button should be removed from the header and accessible from the 3 dots menu.
- The header should be smaller. It takes up a lot of space.
- Make the header expanable: the header should only contain correspondent, subject and date. All other info (cc, bcc etc.) should be hidden and only shown if the header is being expanded.

**Comment by Glitchy-Tozier** [comment]
> The star (favorite) and reply button should be removed from the header and accessible from the 3 dots menu.
I wouldn't do that, it's a very hand feature and hiding it away in the three-dot-menu basically removes this functionality.

It might be a good idea though to allow users to disable it themselves and instead use a functionality like the one suggested in  #1426.
