### ISSUE TITLE
subject line is prefixed with greater signs

### ISSUE THREAD

**Issue by Djfe** [thundernest/k-9#5278]
**Is your feature request related to a problem? Please describe.**
The app doesn't explain what the different greater-than-symbols are for, that it prefixes mail subjects with.
Some mails have no greater sign '>'
others have one or two
```
>
>>
```

![Screenshot_20210427-124920~3](https://user-images.githubusercontent.com/5685512/116230390-e0c60800-a757-11eb-9272-ef1543adfca4.jpg)
Correspondents are displayed before subjects in this screenshot

**Describe the solution you'd like**
If they are supposed to deliver a certain info to the user, then the user should be informed about that in the settings or so.

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/what-do-the-arrows-mean-before-the-second-preview-line/339
