### ISSUE TITLE
"Send email" option when clicking on sender/recipient/from/to instead of only switching to contact book

### ISSUE THREAD

**Issue by PhoenixIV** [thundernest/k-9#5786]
**Is your feature request related to a problem? Please describe.**
In the header of an email, similar to Thunderbird, I would love to have the possibility to write an empty email to that person. The only function available that I am aware of now is "reply" etc.

**Describe the solution you'd like**
I can imagine an options menu popping up when I click on the senders etc. name, including the option "new email".

**Describe alternatives you've considered**
I checked the three-dot- and reply-menu, but could not find a quick access to "write email to" there.

**Additional context**
This might well go along with https://github.com/k9mail/k-9/issues/1119

**Comment by cketti** [comment]
This is now possible in K-9 Mail 6.510 by opening the message details screen, then selecting "Compose message to" from the menu belonging to the list entry for the person.
