### ISSUE TITLE
Switch Gmail users to OAuth if log-in to IMAP/SMTP has failed

### ISSUE THREAD

**Issue by cketti** [thundernest/k-9#6089]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.100-SNAPSHOT

### Problem you are trying to solve

We want users who set up a Gmail account in the past (using password authentication) to be switched over to OAuth, so they can continue to use the app.

However, we don't want to automatically switch over users who intentionally set up K-9 Mail to use an app password. 

### Suggested solution

Since we can't distinguish between regular password and app password, I suggest we don't change the login method when upgrading the app. Instead, the app should only change the login method to OAuth after the login to the incoming or outgoing Gmail server has failed.

**Comment by Dav4555** [comment]
Now I get the auth error for gmail.

**Comment by Dav4555** [comment]
> As there isn't a publicly released version of K9 that supports OAuth2 yet, I'm going to assume you are using version 6.0 or earlier. I will also assume that you have not set up, and configured K9 to use, google's "app passwords".
> 
> If that is the case, then see:
> 
> https://forum.k9mail.app/t/impossible-to-authenticate-with-google/4725/2
> 
> for a pointer to what you need to do to reestablish your K9/gmail authentication.
> 
> If you have questions, you should probably follow up in the support discussion forum at the URL above.

Thank u

**Comment by beankylla** [comment]
Gmail does not authorize applications to login via password anymore:
https://support.google.com/accounts/answer/6010255
