### ISSUE TITLE
Add function to see all marked messages across folders

### ISSUE THREAD

**Issue by Yoneo** [thundernest/k-9#6100]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.000

### Problem you are trying to solve

As user I want to see all with star marked messages unified in one view. That should be done across folders and accounts. But with filter functions I can specify the displayed messages.

Related question: https://forum.k9mail.app/t/how-to-see-all-marked-messages/4740

### Suggested solution

Add below the "unified inbox" a new "all marked messages" button. When the button is tapped, the interface should show all marked messages from all accounts and folders together. In the top menu there should be filter options, that are saved permanently.

### Screenshots / Drawings / Technical details

![image](https://user-images.githubusercontent.com/26109315/172136470-13038274-6791-4c70-af58-df75b4fe15e4.png)

**Comment by cketti** [comment]
This functionality can be achieved once the following features have been added:
- #4513
- #3398
