### ISSUE TITLE
Please provide nightly builds untill the Google issue is solved

### ISSUE THREAD

**Issue by johanw666** [thundernest/k-9#6106]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.100-SNAPSHOT

### Problem you are trying to solve

Using the app with Gmail without activating 2fa on my Google account.

### Suggested solution

Please provide a nightly build, or at least some builds that already support this. 

### Screenshots / Drawings / Technical details

Now I had to compile the app myself, backup the existing one (with Titanium Backup), uninstall, reinstall my own build and restore backup. After that I could select Oauth and, after some warnings because K-9 is not yet approved by Google, access my Gmail account again.

By providing a nightly build version signed with your key the hassle of backup / uninstall / reinstall will go. Now I have to go through the same process again when K-9 is finally approved by Google.

**Comment by shenzhenadam** [comment]
I agree .. We need K-9 mail without any 2FA by Google - I don't use a phone nor do I have any sim card and so I cannot register for 16 number code to enable  Google side .. so we are really stumped without being able to access Gmail on K-9 mail. I have a Yandex account on K-9 - they do ask you to register K-9 on Yandex site and they give you a 16 number code - and you can do that without registering your phone number!

**Comment by navid-zamani** [comment]
… via F-Droid, ideally.  
(If stability permits it. Or F-Droid allows to mark versions as beta/alpha so users that don’t know would automatically skip them.)

**Comment by johanw666** [comment]
> … via F-Droid, ideally.

Is the F-Droid version signwd with the same key as the regular K-9 or with F-Droids key? If it is signed with F-Droids key I'm stuck with the same issue.

**Comment by TheLastProject** [comment]
It's not "nightly builds" but https://github.com/thundernest/k-9/releases/tag/6.100 is out as a beta.

**Comment by johanw666** [comment]
OK that is good enough, at least Gmail works again in this build.
