### ISSUE TITLE
Microsoft 365 Oauth2

### ISSUE THREAD

**Issue by Yannik** [thundernest/k-9#6111]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.000

### Problem you are trying to solve

Since Oauth2 support will be added in 6.200, will logging in to microsoft 365 / exchange online accounts be supported?

### Suggested solution

See above

**Comment by michaelblyons** [comment]
> - [x]  I have used the search function to see if someone else has already submitted the same feature request.

https://github.com/thundernest/k-9/issues/1753, https://github.com/thundernest/k-9/pull/6094

**Comment by Yannik** [comment]
Thanks, @michaelblyons
