### ISSUE TITLE
Disable insecure connections by default

### ISSUE THREAD

**Issue by birdie-github** [thundernest/k-9#6112]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.000

### Problem you are trying to solve

Would be great if the app did **not** allow to use insecure POP3/IMAP/SMTP connections by default. That poses quite a big security risk. By doing so, people will only be able to use SSL based connections (unless they choose otherwise) which cannot be easily sniffed.

### Suggested solution

Settings -> General Settings -> Network -> [x] Disable insecure connections

**Comment by cketti** [comment]
The current way to automatically set up accounts will always use transport encryption. When using manual setup, transport encryption is selected/enabled by default. 

What kind of risk do you see? A user will have to manually set up an account and intentionally disable transport encryption. Sure we could make it a little bit harder. But that's added complexity and code that has to be maintained. Do you believe the security benefit outweighs the effort?

**Comment by birdie-github** [comment]
That settles it, thanks.
