### ISSUE TITLE
Any plan on supporting KaiOS?

### ISSUE THREAD

**Issue by UnixJunkie** [thundernest/k-9#6118]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

all

### Problem you are trying to solve

I'd like K9-mail to run on KaiOS.

### Suggested solution

Port the software.

**Comment by UnixJunkie** [comment]
Feature phones run KaiOS; not iOS; not Android.

**Comment by cketti** [comment]
KaiOS does not run Android apps. See https://www.kaiostech.com/faq/does-kaios-support-android-apps/

K-9 Mail wasn't written with platform-independence in mind. Porting it to any other platform is not really feasible at this point.

**Comment by UnixJunkie** [comment]
I thought good software should be portable.

**Comment by AtjonTV** [comment]
`I thought good software should be portable.`

I just want to give my useless comment because this is too funny. From the perspective of an Android developer that also knows the basics of what KaiOS is:

Trying to get K-9 to KaiOS would be like trying to put a Horse saddle onto a Fruit Fly.

**Comment by UnixJunkie** [comment]
Ok, I am closing this issue then.

**Comment by UnixJunkie** [comment]
And sorry for the noise, I am just a backend guy; I know nothing about UI, web, etc.
