### ISSUE TITLE
Contact images like favicons

### ISSUE THREAD

**Issue by Ricomanda** [thundernest/k-9#6128]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.100

### Problem you are trying to solve

In my desktop email app eM Client, instead of the colorful circles with letters, corresponding contact images have been displayed for a few months now. Similar to favicons in the browser.

From my point of view, this improves the clarity extremely.

### Suggested solution

It would be great if this feature made it into K9 (at least as an opt-in).

### Screenshots / Drawings / Technical details

Screenshot of eM Client

![grafik](https://user-images.githubusercontent.com/44298441/174861646-886ea3ca-5dc6-472a-a127-1dd03bb2bfc4.png)

**Comment by ByteHamster** [comment]
If you have a contact picture in your phone's address book for that sender, K-9 will take that picture instead of the letter.

**Comment by Ricomanda** [comment]
That's right, but not the feature I want.
Because then you would have to save all sender addresses and provide them with an icon yourself.

eM Client loads the icons automatically.
Probably there are security concerns here. Therefore as opt-in.

**Comment by tod31** [comment]
FairEmail had recently problems with Google (probably) due to this feature and in result removed it from the Play Store version. 

https://github.com/M66B/FairEmail/commit/11ee258a3f2f2575fb450ffc17e9f866898d4052
https://www.ghacks.net/2022/05/19/fairemail-developer-calls-it-quits-and-pulls-apps-from-google-play/

**Comment by cketti** [comment]
We won't include such a feature in the app directly. See #6218.
