### ISSUE TITLE
OAuth for Office365

### ISSUE THREAD

**Issue by sclassen** [thundernest/k-9#6153]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.000

### Problem you are trying to solve

This week (On July 6 2022) Microsoft disabled user/password logins.
After some lash back they were forced to re-enable this type of login.

But it is just a matter of time until they will definitely disable user/password and require all mail clients to use OAuth.

### Suggested solution

Please add OAuth support for Office365 accounts.

**Comment by cketti** [comment]
K-9 Mail 6.200 already supports this. We're only waiting for Microsoft to verify us, so you'll be able to actually use it. 

Personal Microsoft accounts (outlook.com, hotmail.com, etc) are already working fine with K-9 Mail 6.200.
