### ISSUE TITLE
Download Attachments from Drafts 

### ISSUE THREAD

**Issue by simon-mueller** [thundernest/k-9#6156]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.200

### Problem you are trying to solve

I use my drafts folder also as quick and safe method to store files that I need to access from anywhere. However, currently, I can't download attachments from Drafts. It's only letting me upload more attachments.

### Suggested solution

Please make it possible to click on the attachment and download it anytime. Alternatively, place a small icon next to the "delete attachment button" (x).

**Comment by cketti** [comment]
Rather than changing the compose screen to allow downloading/saving attachments, we will display drafts like regular messages and make editing drafts an additional button tap. See #4163.
