### ISSUE TITLE
Allow expanding the message header to display more details

### ISSUE THREAD

**Issue by cketti** [thundernest/k-9#6180]
In the message view screen allow expanding the header area to display more information about a message.

Information to display:
- display name and email address of sender
- display names and email addresses of all recipients (To, Cc, and Bcc if present)
- full date (in the user's local time and the original time including time zone name/offset)

This is similar to what Gmail does:

<img src="https://user-images.githubusercontent.com/218061/180606268-50de752c-13a1-4abd-8952-22e721cf1509.png" alt="gmail_extended_message_header" width=300>

Related:
- #5742

**Comment by robsmith11** [comment]
I agree that it would be very useful to be able to see the email address without having to go into the raw headers.

**Comment by cketti** [comment]
See #6393
