### ISSUE TITLE
automatically save email adresses to system contacts

### ISSUE THREAD

**Issue by KiaraGrouwstra** [thundernest/k-9#6201]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.201

### Problem you are trying to solve

not having to type emails over and over again, without having to think about ensuring they are in my system contacts

### Suggested solution

automatically save to contacts any email addresses i interact with that are not part of existing contacts already

**Comment by cketti** [comment]
We won't save anything automatically to the system contacts. However, auto-completing email addresses you've typed before is certainly something we want to add. See #1006.
