### ISSUE TITLE
Allow not saving the email account password

### ISSUE THREAD

**Issue by patrickbkr** [thundernest/k-9#6202]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.201

### Problem you are trying to solve

I currently own a phone I can't apply full disk encryption to for technical reasons. I think my e-mail account is by far the biggest threat when being stolen. The thief can then access most of the websites I'm registered on by resetting the password.
Thus I'm uncomfortable having my emails accessible when the phone is stolen.

### Suggested solution

Allow optionally not permanently saving the email account password, but ask before each use. More complex schemes such as remembering the password until sceen off or for a specific period of time are possible. But I personally would already be glad when having to type the password in on every single use.

**Comment by johanw666** [comment]
As an alternative, the password could be saved in the Android hardware keystore on Android versions that support that (6+). However, this would making backups with tools like Titanium more complicated because they can't access the keystore.

**Comment by cketti** [comment]
See #5874
