### ISSUE TITLE
Being able to obtain e-mails instantly

### ISSUE THREAD

**Issue by xfarrow** [thundernest/k-9#6214]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

The application allows to retrieve e-mails each 15 minutes, as minimum. 
I'd like to retrieve e-mails as soon as they arrive, like other clients do, if possible.

### Suggested solution

Being able to fetch e-mails in background

**Comment by cketti** [comment]
See https://docs.k9mail.app/en/current/settings/push/
