### ISSUE TITLE
Office365+OAuth not available for custom domain names

### ISSUE THREAD

**Issue by luspi** [thundernest/k-9#6215]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

I read that K9 now supports OAuth for Office365 accounts (Thanks!). My university uses Office365 with a custom domain (and enforces OAuth since August 1), but if I try to set it up in K9 I do not get the option to use the new support for such accounts, only POP and IMAP show up. I guess that there is a check for domain name in K9 to only offer that option when appropriate?

### Suggested solution

Always provide the option to set an email account up using Office365+OAuth, no matter the domain name.

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/how-do-i-add-an-office365-account/5072
