### ISSUE TITLE
OAuth2 - Google requires system account for Android.

### ISSUE THREAD

**Issue by lewri** [thundernest/k-9#6219]
>And K-9 Mail does not require you to add Google accounts as system accounts (that can be used by all installed Google apps).

_Originally posted by @cketti in https://github.com/thundernest/k-9/issues/6082#issuecomment-1141995310_

Just raising as a new issue not to necro the old PR.
We tried today on an Android device to use OAuth2 for a Google managed account, and it immediately took the user to the 'Add Google Account' screen built into the phone. Although previously stated in the PR that using OAuth2 in K9 wouldn't require a system account to be made.

**Comment by cketti** [comment]
Is it an Android One device? See #6167.

**Comment by lewri** [comment]
Looks like it didn't template the issue:

Android Version: 11 (Oxygen OS 11.1.10.10.AC01BA
Device: OnePlus Nord

As far as I can tell, not Android One.

**Comment by lewri** [comment]
@cketti I found a workaround. If you install Firefox and srt it as the default browser, it works as normal (since Firefox doesn't talk to the system)

**Comment by PatrykMis** [comment]
Suggested default browsers and WebViews are [Vanadium](https://github.com/GrapheneOS/Vanadium), [Bromite](https://github.com/bromite/bromite), [Mulch](https://gitlab.com/divested-mobile/mulch), [Ungoogled-Chromium](https://github.com/ungoogled-software/ungoogled-chromium-android) and Firefox.
