### ISSUE TITLE
Support Oauth2 on all domains, not just gmail and outlook

### ISSUE THREAD

**Issue by Destroyinator69420** [thundernest/k-9#6223]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

I want to be able to access my school emails on K9 mail. I need to sign in with OAuth2, but it is only supported on gmail and outlook as far as I am aware. My school emails use gmail on the backend, but I must sign in through my college's domain. Why can I only use OAuth2 on any domain name. What about smaller email providers.

### Suggested solution

Allow OAuth2 on any domain, not just major email providers.

**Comment by cketti** [comment]
See https://forum.k9mail.app/t/how-do-i-add-a-google-workspace-account/5087
