### ISSUE TITLE
Treat single messages as a thread

### ISSUE THREAD

**Issue by zootboy** [thundernest/k-9#6258]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.301

### Problem you are trying to solve

When using threaded view, hitting the beginning or end of a thread will "gate" the next/previous actions (formerly arrow buttons, now swipes) to stay within the thread. This is good; it makes it obvious when you have read all the messages in the thread (it was even better with the on-screen arrow buttons because they would be greyed out). If you open a single message in threaded mode, however, there is no gating. You can swipe to the next thread, but now the behavior changes and swiping does not switch between messages within that thread, it instead moves on to the next thread, even if there are multiple messages in that thread. This is very confusing.

### Suggested solution

Add an option to treat all messages as being part of a thread, even single messages. This would apply the gating rule to all messages, preventing swipe / arrow button actions from ever switching threads.

**Comment by cketti** [comment]
The feature to move to the next or previous message uses the contents of the message list. When opening a thread, another message list screen is opened that only contains messages in that thread. This behavior explains why you can't swipe to messages "outside" the thread. 
When viewing the contents of a folder, there could be a mix of threads and single messages. There's no obvious way how moving to the next/previous message should work. The current behavior is not great, but at least it's consistent. I don't think adding an option to only enable swiping between messages in thread views is a solution to that problem.

**Comment by cketti** [comment]
I think #6505 better describes the underlying problem. Closing this.
