### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by mikolajkaz** [thundernest/k-9#6267]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

I have an email account with aliases, so I can use one account with multiple addresses. But when I added all my 4 addresses, K-9 recognizes them as separate email accounts, e.g. if I have 5 unread emails, I see that I have 20 unread emails in the integrated mailbox. That creates clutter in the app.

### Suggested solution

Add support for aliases by allowing adding a few email addresses for one account. It will synchronize only one (the main address). You can send an email from all your addresses. But you will only see one number of unread messages and one account.

### Screenshots / Drawings / Technical details

![Screenshot_20220831-220048-522](https://user-images.githubusercontent.com/52211482/187771240-b2fe23bf-6218-4f54-b681-8c7357232192.png)

**Comment by njeyaakili** [comment]
is what you are after not covered by:

 "settings/[account]/sending mail/manage identities"?

this allows you to set up an alias and use it for setting the "From:" address on outgoing mail while showing only the inbox for the default account.

**Comment by mikolajkaz** [comment]
I don't see this option. I can only add my aliases as separate email accounts. When I get an email, I get four separate notifications.

**Comment by cketti** [comment]
Like njeyaakili mentioned, what you're looking for is already possible. Only add the account once, then go the account settings and add additional "identities". See https://docs.k9mail.app/en/current/settings/account/#manage-identities

In the future please use the [forum](https://forum.k9mail.app/) for support requests.
