### ISSUE TITLE
show if contact is in addressbooks and let add/edit

### ISSUE THREAD

**Issue by PhilippSchlesinger** [thundernest/k-9#6285]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

Let the user see if a contact is already contained in one of the address book sources

### Suggested solution

Like in thunderbird (see screenshot), give the option to add/modify an already existing contact.

### Screenshots / Drawings / Technical details

![grafik](https://user-images.githubusercontent.com/2735628/189081977-b5f8a257-1d48-4c82-be47-ca7f48a3bad8.png)

**Comment by cketti** [comment]
This is part of
- #6198 
- #6181

Right now tapping the contact picture in the message view will open the contact in the contacts app or offer you to add it to contacts.

**Comment by PhilippSchlesinger** [comment]
@cketti great to see there are a lot of improvements already planned.
thx for the hint regarding tapping the contact picture. That works for the sender only, not for the addressee or for cc fields.
