### ISSUE TITLE
Option to hide previous/next message arrows and to move buttons around

### ISSUE THREAD

**Issue by Savasdotexe** [thundernest/k-9#6295]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

I use the volume keys to navigate to the previous/next emails, so prefer they the arrows above are hidden to save space. I also would like the achieve/delete in the order I prefer.

### Suggested solution

Within the settings there can be an option to drag buttons and hide them in a turn on/off toggle.

**Comment by cketti** [comment]
In K-9 Mail 6.3xx (beta versions) the arrow buttons are already gone because we now support swipe to move to the next/previous message.

There's also a feature request to make the displayed actions buttons configurable. See #5300
