### ISSUE TITLE
Delete spam immediately, without moving to trash folder first

### ISSUE THREAD

**Issue by birdie-github** [thundernest/k-9#6298]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.303

### Problem you are trying to solve

I often need to delete messages from the SPAM folder without moving them to Trash.

### Suggested solution

Would be great if long press on the Delete button allowed to delete them directly and permanently.

**Comment by cketti** [comment]
I don't think the suggestion solution is a good idea. By default long-pressing icons in the toolbar displays a tooltip showing the name of the action or a short description. Replacing that with a destructive action that you can't undo is not great.

There's also already a feature request for "delete immediately".
- #3959

However, I think most people would want spam messages to be deleted immediately, i.e. without moving them to the trash folder first. So we could change the behavior of the delete action when viewing the spam folder to delete the message immediately.

**Comment by schlagi123** [comment]
Should mails located in the spam directory handaled the same way as mails in the trash directory? Or should we add a setting to control this handling by users?

**Comment by cketti** [comment]
I don't think this requires a setting. If it turns out there's a really good reason to disable this behavior, we can add a setting later.
