### ISSUE TITLE
Use DNS BIMI records and Clearbit API service in order to display company logos in list view

### ISSUE THREAD

**Issue by bootika** [thundernest/k-9#6328]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.306

### Problem you are trying to solve

Display as many company logos (avatars) as possible in list view - Visual and usability benefit

### Suggested solution

There are two free options which can be used:

**First option --> DNS "BIMI" records** - this type of DNS record is a specification allowing for the display of brand logos next to authenticated e-mails - https://en.wikipedia.org/wiki/Brand_Indicators_for_Message_Identification
Important! - The BIMI record has an "a" attribute (a=https://url.to/certificate.pem) - the Verified Mark Certificate - which is so far optional (https://powerdmarc.com/your-complete-guide-to-bimi/). You should put a checkbox in the K-9 Settings, unchecked by default: "Allow self issued Verified Mark Certificate logos display" which allows the displaying of self issued BIMI logos. If the checkbox is not marked, only authenticated VMC logos will be displayed. If the checkbox is marked, the "a" attribute (a=https://url.to/certificate.pem) is ignored and all BIMI logos will be displayed.

If BIMI record does not return a valid company logo:
**Second option --> Clearbit API Service** - https://clearbit.com/logo - A free logo API service which allows you to quickly lookup company logos using just their domain. You need to credit them in the credits section of the Settings menu. I have seen this implemented in Spark email client and it works like a charm :)

I think that a cascaded lookup of BIMI records and Clearbit API will populate most of the logos in the list view, providing users a more pleasant visual experience, and also a usability benefit.

Hope my suggestion helps :)

### Screenshots / Drawings / Technical details

![01](https://user-images.githubusercontent.com/40858521/192152962-14427640-8021-4fe2-803b-26853a936b7a.png)

**Comment by cketti** [comment]
We won't include such a feature in the app directly. See #6218.

**Comment by smithbill17** [comment]
+1 Excellent suggestion. Until K-9 includes a solution for avatars, then unfortunately it's not the email client for me (and I suspect a significant percentage of others). Disappointed.

**Comment by jpopovitch** [comment]
I support K-9 not yet supporting BIMI until such time that we know BIMI records can't be utilized for email tracking purposes.
