### ISSUE TITLE
Spam button in notification for single email

### ISSUE THREAD

**Issue by shtrom** [thundernest/k-9#6339]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

I'd like to mark incoming messages as spam immediately from the notification, rather than having to discard the notification, only to later have to mark the message as spam from the inbox.

This is essentially the request from this comment https://github.com/thundernest/k-9/issues/6060#issuecomment-1159089068.

### Suggested solution

Add a  “Spam” button to the single message notification.

### Screenshots / Drawings / Technical details

See screenshots in  https://github.com/thundernest/k-9/issues/6060, replacing “Delete” for “Spam”.

**Comment by cketti** [comment]
This is part of #3530.
