### ISSUE TITLE
RTF signature 

### ISSUE THREAD

**Issue by chris122380** [thundernest/k-9#6362]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.308

### Problem you are trying to solve

Generic looking signature or plain Jane signatures.

### Suggested solution

RTF signature support allowing font sizes, hyperlinks, bold, italics, underline, and images in a email signature.

**Comment by cketti** [comment]
Duplicate of #794
