### ISSUE TITLE
RTF support in compose window

### ISSUE THREAD

**Issue by chris122380** [thundernest/k-9#6363]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.308

### Problem you are trying to solve

Generic plain text emails

### Suggested solution

Composer needs support for bullet lists, number lists, font sizes, bold, italics, underline, embedded images, etc.

**Comment by cketti** [comment]
Duplicate of #1745
