### ISSUE TITLE
Swipe actions: vibrate feedback

### ISSUE THREAD

**Issue by Offerel** [thundernest/k-9#6375]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.308

### Problem you are trying to solve

I would find it useful to have a minimal vibrate feedback, when i swipe left/right far enough to execute the desired action (or multiple actions). This is only a nice-to-have feature, i really loved in a mail client called "Aqua Mail". Would be nice to have this here to.

For exeample swipe left to delete a mail: I swipe only some milimeters and no feedback is there and i can release the swipe action, without to delete the mail. On the other hand, if swipe a little bit more far away, the vibrate feedback is there and if i now release the swipe, the mail gets deleted.

### Suggested solution

Add a absolute minimal/short vibrate feedback to swipe actions.

**Comment by cketti** [comment]
The background color now changes when the item has been swiped far enough. I don't think vibration is necessary for this.
