### ISSUE TITLE
Add Contact & Calendar Support 

### ISSUE THREAD

**Issue by BAProductions** [thundernest/k-9#6400]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.309

### Problem you are trying to solve

Is it possible Add Contact & Calendar sync support support so that Contact apps can access my Contact & Etar calendar can access my calendar just like the most Email clients allow to do?

### Suggested solution

Is it possible Add Contact & Calendar sync support support so that Contact apps can access my Contact & Etar calendar can access my calendar just like the most Email clients allow to do?

**Comment by cketti** [comment]
For contact and calendar sync we recommend using the open protocols CardDAV and CalDAV. Then you can e.g. use DAVx⁵ to sync your contacts and calendars to Android.

**Comment by BAProductions** [comment]
> For contact and calendar sync we recommend using the open protocols CardDAV and CalDAV. Then you can e.g. use DAVx⁵ to sync your contacts and calendars to Android.

I'd rather not as my email provider does not use the open protocols CardDAV and CalDAV
