### ISSUE TITLE
Too large margins around contact icons in the message list

### ISSUE THREAD

**Issue by waclaw66** [thundernest/k-9#6429]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.310

### Problem you are trying to solve

Compared to other clients, the margin around the contact icon in the message list is too large. It's a waste of space at the expense of the message preview.

K-9
![obrazek](https://user-images.githubusercontent.com/15554561/197560550-cc2aabcc-6533-46c0-99cd-9e8031cab613.png)

BlueMail
![obrazek](https://user-images.githubusercontent.com/15554561/197561456-10521275-a490-4f98-9011-e4f670c7fd13.png)

### Suggested solution

Reduce the icon margin.

**Comment by cketti** [comment]
This was done intentionally so the subject and sender name align with the toolbar title. See https://m2.material.io/design/layout/spacing-methods.html#spacing

We're not optimizing layouts to put as much text as possible on the screen. But if you want to make more room for text, you could disable the contact pictures in settings.

**Comment by cketti** [comment]
More work on the message list design is planned (see e.g. #4110). However, it's currently not a priority.
