### ISSUE TITLE
Mailbox marks are disturbing in integrated view

### ISSUE THREAD

**Issue by waclaw66** [thundernest/k-9#6430]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.310

### Problem you are trying to solve

Those small mailbox marks on the left side from the Subject are quite disturbing in integrated mode.
Please move them to the left or right side and make them longer.

Before
![obrazek](https://user-images.githubusercontent.com/15554561/197564016-6daa97d4-99dd-43c8-ab29-8c96c236fd0d.png)

### Suggested solution

After (1)
![obrazek](https://user-images.githubusercontent.com/15554561/197563342-e8ddd387-a56f-48e0-b112-623f601e4bb8.png)

After (2)
![obrazek](https://user-images.githubusercontent.com/15554561/197564327-c9437ff4-0a6a-4ff0-a844-6aa0736b3319.png)

**Comment by sozifa** [comment]
second that - full height,  to the left and a bit thicker

**Comment by Snailhail** [comment]
Could make It conditional ; If integrated mode Is enable, or available In options list.
