### ISSUE TITLE
Hide sub-mailboxes folders

### ISSUE THREAD

**Issue by ASLLR** [thundernest/k-9#6441]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

Hi everyone, 

On my environment i'm connecting to K9-mail with a Zimbra Server with IMAP\SMTP protocols. 

We use 2 types of mailboxes, the personnal mailbox and service mailbox. The service mailbox is sharing with all the personnal mailbox and when we connect the personnal mailbox to K9 we've see the service mailbox as a subfolder, with all of his subfolder too and we have a long list of folder. 

This is what i see on app: 

-personal.mailbox/INBOX
-personal.mailbox/INBOX/FOLDER1
-personal.mailbox/SENT
-service.mailbox/INBOX
-service.mailbox/INBOX/FOLDER1
-service.mailbox/SENT
[...]

I can see the issue #630 but i think this is different, even if this issue would allow us to see more clearly.

Thank in advance, 

### Suggested solution

I think an option allowing us to see only the main box (personal) and not those shared with us could be a track.

**Comment by ASLLR** [comment]
Hi @cketti thank you for your answer. 

When i try this i lost all my folders on the app view. I think is because the tree i've write on my issue is not realistic. This is like this : 
-INBOX
-INBOX/FOLDER1
-SENT
-service.mailbox/INBOX
-service.mailbox/INBOX/FOLDER1
-service.mailbox/SENT
[...]

Thank you in advance,

**Comment by cketti** [comment]
You could either manually hide all `service.mailbox` subfolders (see https://docs.k9mail.app/en/current/settings/folder_classes) or wait for #630 to be implemented.

Hiding a particular folder and all of its subfolders basically requires #630. So there's no point in having a separate issue.
