### ISSUE TITLE
Real true black theme

### ISSUE THREAD

**Issue by R7010A** [thundernest/k-9#6478]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.312

### Problem you are trying to solve

Hi guys,
the "dark theme" isn´t black, but grey.
Is it possible to make a real dark AMOLED theme?
This would improve the useabiltiy dramatically.
Thx

### Suggested solution

Just add another selection "black"

**Comment by cketti** [comment]
There are currently no plans to add a "true black" theme.
