### ISSUE TITLE
Option to see Google's category folders

### ISSUE THREAD

**Issue by RafeeDaBoy** [thundernest/k-9#6487]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

Only the basic folders are shown (inbox, draft, spam, etc), but the Google categorized folders aren't shown (Promotions, Updates, Social, etc)

### Suggested solution

It'd be really useful if the Updates, Social, Promotion folders can be displayed as they really help organize everything

### Screenshots / Drawings / Technical details

1. Current K-9 Mail folder tree:
![Screenshot_2022-11-23-09-15-06-46_69738a090b59888d6f9e64a3ebfe2c88](https://user-images.githubusercontent.com/69535896/203463325-302d6182-1a86-4a0c-88f6-97ee3526d526.jpg)

2. Gmail folder tree:
![Screenshot_2022-11-23-09-16-02-41_50ecd26a21c2c56ce608de5e94733463](https://user-images.githubusercontent.com/69535896/203463350-646ab52e-bdf2-474f-b1fd-8352979a8dbc.jpg)

**Comment by cketti** [comment]
It looks like Gmail's category labels are not exposed via IMAP.

We have no plans of using Gmail's proprietary API to support Gmail's proprietary features.
