### ISSUE TITLE
Add support for Android Material You

### ISSUE THREAD

**Issue by ghtesting2020** [thundernest/k-9#6496]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

Currently K-9 Mail does not support Material You (themed icons) in Android 13. Basically it is an icon that is flat, has one set color and the other color follows the users selected theme color. Right now out of the 30 or so Apps I have on my home screen, K-9 Mail sticks out like a sore thumb being one of the only ones that doesn't follow my theme.

Not sure if this would be considered part of the UI/UX design work https://github.com/thundernest/k-9/issues/6488 so feel free to close this ticket and add a task to that one if so.

### Suggested solution

This ticket asks for Material You support light/dark mode.

**Comment by cketti** [comment]
[K-9 Mail 6.400](https://github.com/thundernest/k-9/releases/tag/6.400) includes a monochromatic app icon. See #6307

**Comment by ghtesting2020** [comment]
> [K-9 Mail 6.400](https://github.com/thundernest/k-9/releases/tag/6.400) includes a monochromatic app icon. See #6307

Thanks, K-9 mail rocks.
