### ISSUE TITLE
[Feature Request] Add dark blue theme

### ISSUE THREAD

**Issue by Palloxin** [thundernest/k-9#6527]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.400

### Problem you are trying to solve

Lack of themes

### Suggested solution

Add a new theme pleasant to the eyes: dark blue.
![Screenshot_20221209-121243](https://user-images.githubusercontent.com/75091899/206851892-fe7fc179-88a9-411c-a46e-d873ec6974a9.jpg)
![IMG_20221207_145544](https://user-images.githubusercontent.com/75091899/206851900-8e00e74b-314c-438c-9a44-53eab31fd0e7.jpg)
examples

**Comment by Palloxin** [comment]
the color might variate but the direction is that

**Comment by Henry-Hiles** [comment]
Why was this closed as completed? As far as I can see it has not been added.

**Comment by Palloxin** [comment]
i did a duplicate by mistake
