### ISSUE TITLE
Make accent color configurable

### ISSUE THREAD

**Issue by elhennig** [thundernest/k-9#6567]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.501

### Problem you are trying to solve

With the actual release the compose button and the accent color in the menus cannot be set individually.

### Suggested solution

The accent color should be made configurable in the appearance menu

**Comment by Arnuntar** [comment]
Yes please allow to change that colour.
Pink is not everybody's Cup of tee 🙏

**Comment by RequestPrivacy** [comment]
Thanks for the compose FAB! Great addition...
That being said, I would also love an option for choosing custom colors since pink isn't my style either.

**Comment by MarcusWolschon** [comment]
... And maybe not PINK as default while at it.

**Comment by cketti** [comment]
Adding any setting is adding maintenance cost to the app. In this case it would be substantial because themes can't be changed dynamically. We'd have to dynamically set the color of every UI widget that uses the accent color.

So we're not going to add this feature.

**Comment by elhennig** [comment]
So, does thst mean the pink button stays like it is? Can you use the accent color defined in the system at least?

**Comment by cketti** [comment]
Dynamic color is only part of Material 3 (also called Material You). Right now we barely support Material 2. So we won't get to that for a while.

**Comment by MarcusWolschon** [comment]
This this one is closed as WontFix, I opened a different ticket to at least replace that terrible PINK
#6575
