### ISSUE TITLE
Replace ugly pink  accent color 

### ISSUE THREAD

**Issue by MarcusWolschon** [thundernest/k-9#6575]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.501

### Problem you are trying to solve

Replace that ugly pink with another colour

### Suggested solution

A neutral, unsaturated colour

**Comment by cketti** [comment]
Please mind your wording. If you call something ugly, you're not making an argument.

We'll most likely switch to another color for the floating action button, but keep the pink as secondary color.

**Comment by elhennig** [comment]
Colors a re a matter of taste of course. So the way I would recon as best would be to make the color configurable. Some people - including me - do not like the pink at all, others will definitely have a problem with any other color you choose.
The reason could always be personal preferences or that it just does not fit the the design people have on their phones.
You just can't get it right for everybody, 

BTW, FairEmail has no configurable theming either, but at least some 5 or 6 different color schemes to choose from.

**Comment by MarcusWolschon** [comment]
Oh god no, keeping pink on an otherwise greyscale for checkboxes and headers?
It's not like there's hundreds of years of colour theory out there and Google even offering a generator for colour themes that complement each other at material.io .

How is "we'll most likely do something about this issue" closing the issue?
