### ISSUE TITLE
Importing account and identities settings from Thunderbird prefs.js

### ISSUE THREAD

**Issue by ysalmon** [thundernest/k-9#6577]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.501

### Problem you are trying to solve

Due to version 6.510 loop crashing on my device, I made the mistake of trying to uninstall it then install an earlier version. Which apparently caused the loss of my whole configuration.

Configuring the many accounts and many identities/signatures I have within K9 is tedious (unavoidably, I think, because of the constraints of the form factor).

### Suggested solution

A tool parsing my Thunderbird profile's prefs.js and generating a suitable configuration file for K9-mail to import would be great.

Meanwhile, a description of that configuration file format (I could not find it in the doc) would allow me to write it "by hand" on my computer.

**Comment by ByteHamster** [comment]
> Meanwhile, a description of that configuration file format (I could not find it in the doc) would allow me to write it "by hand" on my computer.

Just export an example file and follow the structure that is already there ;)

**Comment by ysalmon** [comment]
That's what I ended up doing, even if I would have liked to know the minimum subset needed (lots of default settings). Anyway, it allowed me to see that 6.501 starts crashing the very moment you create an account in it…

Here is my code, if that helps somebody : https://framagit.org/-/snippets/6864

**Comment by cketti** [comment]
Adding support for syncing settings between Thunderbird instances (including between desktop and mobile) is on the [roadmap](https://developer.thunderbird.net/planning/android-roadmap).

But I don't see us adding support for parsing `prefs.js`. So I'm closing this issue.
