### ISSUE TITLE
Support domain aliases

### ISSUE THREAD

**Issue by kuxv** [thundernest/k-9#6589]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.400

### Problem you are trying to solve

I have multiple aliases on the same domain, like me1@domain.com and me2@domain.com where me2 points to me1. When I reply a mail addressed to either of those I would like the composed message's "from:" field match the received's "to:" field. Currently the only workaround I can see is to create 2 separate identities me1 and me2 and switch between them when replying. However the drawback is that both identities receive all the messages so they are kind of duplicate.

### Suggested solution

It would be great if the "from:" field is prefilled with "to:" field for replies.

**Comment by cketti** [comment]
K-9 Mail already supports multiple identities per account. When replying to a message the identity a message was sent to is automatically used for replying.
See https://docs.k9mail.app/en/current/settings/account/#manage-identities

Identities in K-9 Mail are only used for sending. So there's no "both identities receive all the messages".

**Comment by kuxv** [comment]
You are absolutely right! I was unable to find that. I've just tested it and it works. Thanks a lot!
