### ISSUE TITLE
Change translation [Polish]

### ISSUE THREAD

**Issue by blazeyzem** [thundernest/k-9#6663]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.400

### Problem you are trying to solve

There is a problem displaying all function buttons on system notification.
There are three buttons Open, Mark as read, Delete. Polish translation is Otwórz, Oznacz jako przeczytane, Usuń.  Second button translation is to long and Delete button does't show at all. 

### Suggested solution

Please change Oznacz jako przeczytane as Przeczytane . That is enough to understand what is this button for. 

### Screenshots / Drawings / Technical details

![Screenshot_2023-02-13-17-02-55-602_com teslacoilsw launcher-edit](https://user-images.githubusercontent.com/22093065/218511018-00326793-d0c7-4d44-b700-a4d4bea10973.jpg)

**Comment by cketti** [comment]
I changed the string on [Transifex](https://www.transifex.com/k-9/k9mail/).
