### ISSUE TITLE
Biometric/Password

### ISSUE THREAD

**Issue by kubatron** [thundernest/k-9#6688]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.508

### Problem you are trying to solve

None auth to app.

### Suggested solution

I would liie to suggest implement biometric or password lock app for additional security and 2FA (yubikey) when app detect new login or trying use brute-force.

**Comment by cketti** [comment]
See #753
