### ISSUE TITLE
Migrate to Glide to Coil

### ISSUE THREAD

**Issue by Goooler** [thundernest/k-9#6691]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.508

### Problem you are trying to solve

Migrate to Glide to Coil with better integration with Kotlin & Coroutines, and we can easily use Compose in the future.

### Suggested solution

https://github.com/coil-kt/coil

**Comment by cketti** [comment]
Please don't create feature requests like this one. The technical direction of the app is decided by the development team. We'll create issues if and when that becomes necessary.
