### ISSUE TITLE
(beta) consider changing the message list line height when preview lines change

### ISSUE THREAD

**Issue by vagner-dias** [thundernest/k-9#6694]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.508

### Problem you are trying to solve

Hi!

Please consider changing the message list line height when preview lines change so that there is no excessive space between lines.

Here are som examples:

Message preview: 2 lines

![Screenshot_20230221-123932](https://user-images.githubusercontent.com/86367839/220391423-be466a3e-8aa8-4c9f-ac73-9632772889b9.jpg)

Message preview: 0 lines

![Screenshot_20230221-123947](https://user-images.githubusercontent.com/86367839/220391529-7b869c19-2dd8-4abf-992c-7fe9a3685db5.jpg)

### Suggested solution

Adjust the message list line height according to the number of preview lines chosen (noticed when switch between 0 and 2 lines)

**Comment by cketti** [comment]
This has already been implemented in #6637 (but the change hasn't been included in a beta version yet). It won't make a huge difference when the star is displayed, though (see #6683).
