### ISSUE TITLE
Folder visible in search results

### ISSUE THREAD

**Issue by Maetts** [thundernest/k-9#6724]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.508

### Problem you are trying to solve

When searching across the mailbox it is not visible in which folders the mails are e.g. Inbox, Sent, Trash. 

### Suggested solution

Add a label for the folder of the mail in search results e.g. Inbox, Sent, Trash.

**Comment by cketti** [comment]
The folder name is displayed at the bottom of the message details screen.

I don't think the folder name is important enough to warrant adding it to the message list (which is already complex enough). We do have plans to improve search so it can be limited to a set of folders. See #4513.
