### ISSUE TITLE
Add a way to clear data stored on the device by k9

### ISSUE THREAD

**Issue by Massedil** [thundernest/k-9#6741]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.509

### Problem you are trying to solve

Day after days, by using k9 and searching in some of my folders by loading e-mails, the app database size growing. k9 is now using 147Mo of user data.

The folder `com.fsck.k9/databases` uses 135.7Mo.

There is no way to unload a folder or all folders.

### Suggested solution

It can be interesting to have a way to see and clear local data (without deleting it from the server) :
- in the folder view, display the space used by the folder after its name
- add a way to remove the cached data for each folder with a long click on the folder's name
- in the k9 parameters settings, add an option to clear all cached messages

**Comment by Massedil** [comment]
> Go to _Manage folders_, open the folder settings screen of a folder, then select _Clear local messages_ from the menu.

Thanks, I did not know ! 

It can be useful to have the local size of all folder in this view to see which one is using all the storage space

**Comment by sudwhiwdh** [comment]
> Go to Manage folders, open the folder settings screen of a folder, then select Clear local messages from the menu.

Is this also available as a global action for the individual account?

And for data security reasons I wonder: Local messages deleted from a folder using "Clear local messages" are then safely deleted from the device or not visually retrievable until they are downloaded again via IMAP?

**Comment by cketti** [comment]
> Is this also available as a global action for the individual account?

No.

> And for data security reasons I wonder: Local messages deleted from a folder using "Clear local messages" are then safely deleted from the device or not visually retrievable until they are downloaded again via IMAP?

Removing local messages will never be a security feature. If you require sensitive messages to not be stored on the device, please use an email client that only downloads messages on demand and doesn't store a local copy.
