### ISSUE TITLE
hide folders option

### ISSUE THREAD

**Issue by ghtesting2020** [thundernest/k-9#6748]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.509

### Problem you are trying to solve

Please add option hide folders in individual folders.

### Suggested solution

Add option to hide individual folders.

**Comment by cketti** [comment]
As mentioned, this is already possible using folder classes. Improving folder management (including making it easier to hide folders) is on the roadmap.
