### ISSUE TITLE
Surround URL pasted from clipboard with angle brackets when composing a message

### ISSUE THREAD

**Issue by cketti** [thundernest/k-9#6756]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.509

### Problem you are trying to solve

Sometimes people compose text and include URLs in parentheses. This presents a challenge to apps trying to linkify URLs in this text because `(` and `)` are valid characters in a URL that don't have to be encoded.

Examples:
* `some text here (https://domain.example/path)`
* `(some text here: https://domain.example/path)`
* `(some text here and then a URL on a new line`
  `https://domain.example/path)`
* `(some text here :) https://domain.example/path)`
* `(some text here https://domain.example/path_(still_part_of_the_url))`

`https://domain.example/path)` is a valid URL, but probably not what the sender meant.

For a human reader it's mostly easy to see what is part of the URL and what is part of the surrounding text. However, I hope you can see that a piece of code trying to come to the same conclusion gets very complex pretty soon.

### Suggested solution

Make things easier for apps trying to find URLs in plain text, by surrounding URLs pasted from the clipboard in angle brackets (that can't be part of a URL in their unencoded form).

The examples from above turn into:
* `some text here (<https://domain.example/path>)`
* `(some text here: <https://domain.example/path>)`
* `(some text here and then a URL on a new line`
  `<https://domain.example/path>)`
* `(some text here :) <https://domain.example/path>)`
* `(some text here <https://domain.example/path_(still_part_of_the_url)>)`

**Comment by hmncube** [comment]
@cketti In the case that the user pastes in some texts with a link like `This is a link https://link.com` do we convert the text to `This is a link <https://link.com>` or the angle brackets should only be added when a link is pasted with no other text like `https://link.com`.
Should I also handle linked without the `http` or `https` part eg `www.link.com`?

**Comment by cketti** [comment]
Only pasted text that consists solely of a URI supported by `UriMatcher` should be surrounded with angle brackets.
