### ISSUE TITLE
Add Archive  button for notifications

### ISSUE THREAD

**Issue by AyushmaanAggarwal** [thundernest/k-9#6802]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.400

### Problem you are trying to solve

Notifications only allow for mark as read, delete and replying to emails

### Suggested solution

I would love it if I had the option to change the delete email button in notifications to archive as this is how I've set up my gmail app and allows me to keep a record of all the emails I may have deleted.

**Comment by cketti** [comment]
This will be possible once #3530 is implemented.
