### ISSUE TITLE
Recognize `--&nbsp;` as signature delimiter

### ISSUE THREAD

**Issue by raboof** [thundernest/k-9#6808]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.510

### Problem you are trying to solve

Get the nice signature separation functionality even when senders send questionable HTML emails.

Specifically, the Fastmail web interface currently makes it impossible to use a `-- ` separator and only allows setting a `--&nbsp;` separator. The GMail web interface correctly interprets those, but K-9 currently doesn't.

### Suggested solution

Also support `--&nbsp;` as signature delimiter for HTML emails

**Comment by cketti** [comment]
K-9 Mail currently doesn't try to detect signatures in HTML parts at all. So even if Fastmail were using `-- ` as separator, it wouldn't help.

**Comment by raboof** [comment]
It does at least strip them on replies (#6279 / https://github.com/thundernest/k-9/blob/main/app/core/src/test/java/com/fsck/k9/message/signature/HtmlSignatureRemoverTest.kt), right?

**Comment by cketti** [comment]
You're right. I was only thinking about displaying the message.
