### ISSUE TITLE
Dark widget please

### ISSUE THREAD

**Issue by Maetts** [thundernest/k-9#6821]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.600

### Problem you are trying to solve

Dark widget when dark mode. I know there are prios but please.. 

### Suggested solution

Dark widget would be a very pleasant surprise

**Comment by ByteHamster** [comment]
Duplicate of #3728
