### ISSUE TITLE
Display non-ASCII headers using charset from Content-Type

### ISSUE THREAD

**Issue by mikhirev** [thundernest/k-9#6898]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.702

### Problem you are trying to solve

Some senders don't encode non-ASCII characters in headers like `Subject`, `From`, `To` etc. Yes, this violates RFC5322, but many clients display them correctly according to the Postel's law. The consequence is that sender does not notice the issue or assume that the problem is on receiver's side.

### Suggested solution

If the `charset` is specified in the `Content-Type` header, try to display non-ASCII characters in headers using that character set.

**Comment by cketti** [comment]
> If the `charset` is specified in the `Content-Type` header, try to display non-ASCII characters in headers using that character set.

We won't be doing that. Messages that require such a mechanism are clearly broken and the software generating such a message needs to be fixed.
However, it's much more likely that a message you're having trouble with uses [RFC 6532](https://datatracker.ietf.org/doc/html/rfc6532) (Internationalized Email Headers). We'll add support for that eventually.

See #2633

**Comment by mikhirev** [comment]
> Messages that require such a mechanism are clearly broken and the software generating such a message needs to be fixed.

Yes, I agree. However the feature I requested wouldn't break anything in K-9 Mail and would improve user experience.

> However, it's much more likely that a message you're having trouble with uses [RFC 6532](https://datatracker.ietf.org/doc/html/rfc6532) (Internationalized Email Headers).

Unfortunately it's not. It is not UTF-8 (CP1251 in this particular case).
