### ISSUE TITLE
Exchange ActiveSync, no WebDAV or anything else available

### ISSUE THREAD

**Issue by firefoxlover** [thundernest/k-9#6899]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.601 F-Droid

### Problem you are trying to solve

[This blog post](https://codethis.wordpress.com/2011/01/07/an-inside-look-at-exchange-support-in-k-9-mail/) and [this wiki entry](https://github.com/thundernest/k-9/wiki/K9MailAndExchange) both show that some form of Exchange is supported.

Do all Exchange ActiveSync servers support IMAP? Because there is only POP3 and IMAP available.

### Suggested solution

If the servers also allow IMAP, it doesnt matter. Maybe detect things better:

- the SMTP security is detected wrongly, it is STARTTLS in my case
- the domain is not detected, while the servers use the weird `domain\username` scheme. This is not the mail adress in my case

with these changes in my case the server works, receiving and sending to an external server tested.

So adding a "IMAP with Microsoft Exchange-Server" button detecting these things would already be enough I guess.

It seems in older releases Exchange was supported. Why removed? Was that the old standard?

I dont care about microsofts proprietary stuff at all and understand if nobody wants to implement that. But having compatibility is essential.

**Comment by cketti** [comment]
K-9 Mail supported WebDAV at some point, but does not anymore. The code was unmaintained for years. And as far as I can tell WebDAV isn't supported by modern Exchange server versions anyway.

I've removed the outdated wiki page.

Current versions of K-9 Mail don't have any discovery mechanism for server settings. Automatic setup only works for a handful of domains from large email providers. See https://github.com/thundernest/k-9/blob/4f0ee47d12bc1e9a4f436d182e97916626c64377/feature/autodiscovery/providersxml/src/main/res/xml/providers.xml

We're currently working on adding support for Thunderbird's Autoconfig mechanism, see #865. This will still require the admin of an Exchange server to do manual work in order for the correct IMAP/SMTP settings to be automatically picked up by clients.
