### ISSUE TITLE
Delete manually trusted TLS certificate

### ISSUE THREAD

**Issue by dlehmenk** [thundernest/k-9#6970]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

I manually accepted an untrusted certificate, because I'm sure it is valid but slightly misconfigured. Afterwards I wanted to notify my provider about this, but neither could I review the error message, nor delete the accepted cert, so it would show up again. Then I thought it would be useful in any case to be able to remove manually trusted certs, in case one accidentally accepted it. I look at the docs, wiki and issue tracker, but could not find any information on this, so I'm assuming this might not be implemented?

### Suggested solution

Have a GUI-Option to delete manually trusted certificates

**Comment by cketti** [comment]
You can remove stored certificates by going to server settings, changing the server name and/or port to some other value (doesn't need to point to an existing server), then press the "Next" button. Afterwards change it back to the original settings, and press "Next" again. You'll again be prompted to accept the certificate (if it's not trusted).

**Comment by dlehmenk** [comment]
Ah, alright, thank you! Then I'm closing this again for the moment, if you still want to implement or document this, feel free to reopen.
