### ISSUE TITLE
Receive field just says "Me" instead of showing email address

### ISSUE THREAD

**Issue by gocomala** [thundernest/k-9#6985]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

When a user has multiple email accounts, it's not useful to only display "Me" in the "To" filed.  It's a nuisance to have to open the email, and click on the From/To field to read the details.

### Suggested solution

Please show the email address to which an email was sent instead of just showing "Me".

**Comment by cketti** [comment]
A message belongs to a particular email account. If "to me" is displayed, it means the message was addressed to the only email address (identity) belonging to the account.

**Comment by gocomala** [comment]
> A message belongs to a particular email account. If "to me" is displayed, it means the message was addressed to the only email address (identity) belonging to the account.

Yes cketti, if I am only viewing one account, then it is obvious to which account it is addressed.  When viewing the Unified Inbox, where I see the latest emails for all 7 accounts, then the problem described applies.

**Comment by cketti** [comment]
When opening a message from a list containing messages from multiple accounts (Unified Inbox, search results), the account name is displayed above the message subject.

<img src="https://github.com/thundernest/k-9/assets/218061/53c152d0-f16d-4214-8fd1-56ff1553585e" alt="image" width=300>

**Comment by gocomala** [comment]
> A message belongs to a particular email account. If "to me" is displayed, it means the message was addressed to the only email address (identity) belonging to the account.

Yes cketti, if I am only viewing one account, then it is obvious to which account it is addressed.  When viewing the Unified Inbox, where I see the latest emails for all 7 accounts, then the problem described applies.

> When opening a message from a list containing messages from multiple accounts (Unified Inbox, search results), the account name is displayed above the message subject.
> <img alt="image" width="300" src="https://user-images.githubusercontent.com/218061/246393404-53c152d0-f16d-4214-8fd1-56ff1553585e.png">

Ah- I'm so accustomed to look in the To field, I never noticed the box above the subject.  It's not very intuitive up there, but totally easy to get used to it.  Thanks!
