### ISSUE TITLE
Menu Redesign

### ISSUE THREAD

**Issue by harish-kumaran** [thundernest/k-9#6996]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.706

### Problem you are trying to solve

The present menu screen which displays all the Inbox, Sent, Trash, Junk, etc. has a few usability issues in my humble opinion.
The hamburger button to open the menu is placed in the top left corner of the screen.
This button in my opinion will be the most used inside the whole app experience.
Even though, there is a left swipe gesture to open this menu, it is not useful. Since Android 10, Gesture based navigation took over the three button navigation in most devices as the default and <b>almost all users</b> have gotten used to it. This gesture based navigation collides with the swipe gesture to open the menu hence making it useless in <b>almost all usecases.</b>

### Suggested solution

Hence, I would suggest to (re)move the hamburger button above the compose icon placed as a floating button.
Matrix's flagship client recently redesigned their client where they changed the menu button and got great response from its users (infact the suggestion was actually made by the users). 
So I have attached the images what I talk about, looking at the images I hope you will be able to understand.

### Screenshots / Drawings / Technical details

![Element Menu Button](https://github.com/thundernest/k-9/assets/135484820/0b968fc6-f2a8-437f-b270-ad68a4975966)
![Element Space Menu](https://github.com/thundernest/k-9/assets/135484820/7f1e633d-4989-4170-b126-d694da41fd0a)

**Comment by harish-kumaran** [comment]
@cketti Although this would be the first time designing the menu like this on an email client in smartphone, I am pretty sure everyone would like it. Please ask about this to the community/users about their feedback on this :)

**Comment by harish-kumaran** [comment]
Note: Even though there is a toggle to disable unified inbox, my suggestion is to disable it automatically when there is only a single account.

**Comment by cketti** [comment]
We currently don't have plans to change the UI in such a way.

**Comment by harish-kumaran** [comment]
> We currently don't have plans to change the UI in such a way.

Okay.
By the way say whether this kind of design is better than the present design in terms of "ease of use"?
