### ISSUE TITLE
Subject in Message List Preview

### ISSUE THREAD

**Issue by harish-kumaran** [thundernest/k-9#6997]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.706

### Problem you are trying to solve

I would like to be able to preview the subject of the mail in the message list rather than the body of the mail.

### Suggested solution

Add an option to either display the subject or the body of the mail in settings.
Also make sure to enable the ability to customize the no. of preview lines for this as well.

**Comment by harish-kumaran** [comment]
> What are you asking for exactly? The subject is already displayed in the message list. If you want to, you can display the sender name above the subject (see <https://docs.k9mail.app/en/6.400/settings/general/#correspondent-above-subject>).

I am asking to display the Subject in the list of the messages rather than inside the message view.
You see all the messages in a place right? there, I am asking to display subjects of the message
You have given option to display the body of the mail and also preview lines for it.
Similarly give an option to show subject there instead of the body of the mail.

**Comment by cketti** [comment]
Your request still doesn't make sense to me. The message list looks like this:

![image](https://github.com/thundernest/k-9/assets/218061/09e8724c-05fb-4fe9-b793-3b3691b08ba6)

The subject of a message is displayed at the very top of each list item. There's no setting to hide the subject. So it's not clear to me why you're not seeing the message subjects in the message list.

**Comment by harish-kumaran** [comment]
> Your request still doesn't make sense to me. The message list looks like this:
> 
> ![image](https://github.com/thundernest/k-9/assets/218061/09e8724c-05fb-4fe9-b793-3b3691b08ba6)
> 
> The subject of a message is displayed at the very top of each list item. There's no setting to hide the subject. So it's not clear to me why you're not seeing the message subjects in the message list.

I am extremely sorry it was a fault on my side.
The present behaviour is what I wanted. I misunderstood the current behaviour.
Thanks 👍
