### ISSUE TITLE
Choose Sent and Trash folder

### ISSUE THREAD

**Issue by flagoda** [thundernest/k-9#7053]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

Change folder when mail gone when delete or sent (Sent and Trash)
Because not same folders on the imap server and don't see them on the server

### Suggested solution

possibility to choose folder on settings

**Comment by cketti** [comment]
In the future please use the [forum](https://forum.k9mail.app/) for support requests.
