### ISSUE TITLE
K-9 Mail v6.707 No Download APK?

### ISSUE THREAD

**Issue by tigernero79** [thundernest/k-9#7066]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

K-9 Mail v6.707

### Problem you are trying to solve

I realized that the K-9 Mail v6.707 version, unlike the previous ones, only brings the download of the source code files and no longer the compiled apk file, is this a deliberate thing or an oversight? It's convenient to always test the latest versions. Thank you to those who will answer me

### Suggested solution

create apk

### Screenshots / Drawings / Technical details

![Senza titolo](https://github.com/thundernest/k-9/assets/35575744/d2d238d8-cf1f-42e8-8ede-03298dcd7c9c)

**Comment by njeyaakili** [comment]
See the note on the release item for 6.707
 
    <https://github.com/thundernest/k-9/releases/tag/6.707>

    (GitHub seems to have trouble processing the APK upload. 
    Please install from F-Droid or Google Play once this version 
    becomes available)

I assume that if this issue persists on future releases it will be looked at in more depth.

**Comment by cketti** [comment]
I was able to add the APK to the release just now.
