### ISSUE TITLE
Create the web engine email viewer as a separate process and kill it once the app is left

### ISSUE THREAD

**Issue by birdie-github** [thundernest/k-9#7083]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.707

### Problem you are trying to solve

I'm not a Java programmer but it feels like K-9 mail could be improved by spawning the web engine email viewer as a separate process and killing/stopping it once the app has been put to background or closed.

Why is this necessary? Currently once you open an email or two, K-9 Mail's RAM use spikes up to 500MB and stays there which doesn't sound nice for such a tiny email client.

### Suggested solution

See above.

**Comment by cketti** [comment]
While not exactly the same issue, I think we can combine this with #6460.
