### ISSUE TITLE
Option to Control Order of Emails When Retrieving from Server

### ISSUE THREAD

**Issue by liboyan666** [thundernest/k-9#7133]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.5.0

### Problem you are trying to solve

Currently, when fetching emails from the mail server, regardless of the number of emails requested, the most recent emails are always displayed at the end of the list. This affects the presentation of the email list, especially for users who prioritize processing the latest emails.

### Suggested solution

 I propose adding a configuration option that allows users to control the order in which emails are retrieved from the server. Specifically, I suggest adding an option that allows users to choose whether the query should fetch emails with the most recent dates first or the oldest dates first.

**Comment by cketti** [comment]
I don't think it's necessary to add a setting to specify the download order. The display order is independent of the order in which messages are downloaded. See https://forum.k9mail.app/t/getting-latest-emails-when-querying-mail-server/7133/3
