### ISSUE TITLE
switch to message list after deleting an email 

### ISSUE THREAD

**Issue by kr-g** [thundernest/k-9#7143]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

Currently.
After deleting an email the next email from the message list is shown. By mistake it is easily possible to press twice and delete this email too.

### Suggested solution

Expected behaviour.
Return to message list and scroll down to the proper position in the list. Or make this feature available in the settings.

**Comment by wmontwe** [comment]
@kr-g there is already a setting available. Just open `Settings` -> `General settings` -> `Interaction` -> and enable `Return to list after delete`

**Comment by kr-g** [comment]
I haven't seen that! Thanks a lot.
