### ISSUE TITLE
High Refresh Rate Support

### ISSUE THREAD

**Issue by seniorm0ment** [thundernest/k-9#7250]
From what I can see, the app does not support high refresh rate. I could be wrong, but compared to other apps it seems a decent amount less readable and smooth when scrolling.

Noticeable when scrolling, also there is a small amount of animation lag when transitioning into mailboxes.

**Comment by wmontwe** [comment]
Thank you for the feedback. We're aware of the issues with high refresh rate support and animation lag. These are on our long-term development roadmap and will be addressed in future updates. We appreciate your patience.
