### ISSUE TITLE
Hide Specific Mailboxes In Unified Inbox

### ISSUE THREAD

**Issue by seniorm0ment** [thundernest/k-9#7273]
The ability to have unified inbox exclude certain accounts from showing would be nice.
I don't want my work account to show messages in there, because it is the only account in which I actually keep stuff lingering in the inbox, rather than archiving it or deleting it when I read it. So it just is a bit cluttered to sit it all mixed in unified inbox with my personal mail.

**Comment by ByteHamster** [comment]
Using the “manage folders” button in the side bar, you can include/exclude specific folders (including the inbox of an account) from the unified inbox.

**Comment by seniorm0ment** [comment]
I am not seeing any options for the unified inbox in manage folders

**Comment by ByteHamster** [comment]
Manage folders -> inbox -> unify

**Comment by cketti** [comment]
@seniorm0ment: In the future please use the [forum](https://forum.k9mail.app/) for support requests.

If you want to request a feature, please search the [user manual](https://docs.k9mail.app) and this issue tracker first to make sure it doesn't already exist. Then make sure to use the proper [issue template](https://github.com/thundernest/k-9/issues/new/choose).
