### ISSUE TITLE
Import/export (backup/restore) selected mails from/to selected accounts

### ISSUE THREAD

**Issue by osering** [thundernest/k-9#7285]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

newest

### Problem you are trying to solve

So far there is only option Import/export settings.
Although contents / messages are at least of the same importance, their backup/restore is not provided.
Some other email clients provides that functionality, for instance
https://www.kerneldatarecovery.com/blog/save-a-single-email-message-in-msg-eml-rtf-html-and-pdf-formats/
https://support.microsoft.com/en-us/office/export-emails-contacts-and-calendar-items-to-outlook-using-a-pst-file-14252b52-3075-4e9b-be4e-ff9ef1068f91
https://techdelites.com/what-is-the-process-for-exporting-emails-from-the-default-email-app-on-an-android-device/

### Suggested solution

Proposal: Add Import/Export mail (in different open formats (for instance ".eml", ".mbox", ".txt"), including attachments/signatures and/or not, etc) as other mail clients offer. This is extremely important when using POP3 mail provider (some more privacy orientated, free mail providers still offer that)  where Sent mail cannot be synced and is located only on each local device. 
Could be also just some selected email export/import as well as export just one selected account or just some selected emails.
& import of as replacement (rewrite account, deleting all contents) or add to specific account (checking, if no duplicates).
gziping/7zipping etc or archiving mails by years/months could be implemented.
Give users possibility to change saved file name wildcards.

This could lessen vendor lock-in and make it easier to transfer mails from one email client to another.

**Comment by cketti** [comment]
Duplicate of #3627

**Comment by osering** [comment]
### Considerations:

1) List of duplicates just show that people consider this functionality as essential/basic already for 4 years and it's not still implemented (been ignored). No any answer since 2019 - why.

2) Thunderbird as the present aspiration for K-9 (after marriage) does not consider such functionality as superfluous: Thunderbird's export tool lets you create a backup of your Thunderbird profile including accounts, messages, address books, and settings. (https://support.mozilla.org/en-US/kb/thunderbird-export). Why not take it as good practice at least now to sync user experience?

3) You propose using IMAP instead of POP3 if using more than one client (which we do not find in K-9 documentation). Unfortunately it's up to provider, not end-user which protocol/port to use, and POP3 is still quite widespread, and sometimes - the only option. 
It's hard to disagree that POP3 is not the best protocol in 21-st century. But as we know, all email protocols/standards are **ancient, obsoleted, flawed, inherently insecure** by default (rarely patched with PGP/GPG e.t.c). Moreover, biggest email providers and govt's abuse these vulnerabilities and privacy at mass scale (on servers scan email content). As such **email as such should be avoided at all by every reasonable man**.

But then, why we need privacy-oriented K-9? Is it honeypot for privacy geeks?
