### ISSUE TITLE
Account (POP3) sync/backup OTA

### ISSUE THREAD

**Issue by osering** [thundernest/k-9#7286]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

latest

### Problem you are trying to solve

There is no functionality to regularly backup local mail data from device.
Here problem is highlighted:
https://discussions.apple.com/thread/5868044
(A POP account will not sync content across multiple devices. It only saves content on the local machine. So, as you have found, the sent items from one device can only be seen on the one device.)
P.S. Connected to issue #7285

### Suggested solution

Option to regularly (lets say, when home Wifi is available) OTA sync/backup POP3/? accounts  (to circumvent POP3 protocol deficiencies) accounts (all local mails) among at least K-9 and desktop Thunderbird/(Gnome)Evolution versions. 
Settings could also be synced the same way, simultaneously.
Probably Synchthing app could be used for this functionality.

**Thunderbird/k-9 could be the first email client ever to solve global old POP3 sync problem.**

**Comment by cketti** [comment]
We have no intention of adding support for synchronizing messages between email clients directly. If you want to access your emails using multiple clients, you can use the IMAP protocol.

**Comment by osering** [comment]
### After-party Considerations:
If K-9 is advertised (for instance, in F-droid) as capable of "automatic background synchronization or push notifications" (without mentioning that this applies only to few usecases with IMAP or some privileged folders) why unified/complete mail account/mailbox/folder sync is even beyond "intentions" although in 21-st century most of us uses more than one client (at least desktop and mobile one)? Or is it intentionally misleading advertising to attract more inexperienced users?
User content is of paramount importance and not to be dumped/lost with the specific device.
P.S. POP3 or IMAP protocol is not free choice of user, but dependent on email provider only.

If not "directly" - **syncthing.net** was proposed as the best in it's class wildly popular cross-OS opensource "connector". If fine-grained automatic/scheduled (mail account/folder) backup feature would be present in K-9, it could accomplish the rest (sync part) ...
Some usecase links:
https://news.ycombinator.com/item?id=35879375
https://news.ycombinator.com/item?id=10559182
https://proprivacy.com/cloud/review/syncthing

**Why to avoid/afraid being the BEST CLIENT around with unique functionality (be the #1 option at least for quite wide POP3 protocol user base - especially of freemails - on Android)?**
