### ISSUE TITLE
Determine message's folder

### ISSUE THREAD

**Issue by patricktokeeffe** [thundernest/k-9#762]
When viewing a message from search results on a unified folder, it's difficult (impossible?) to determine what folder the message is contained in. Possible solutions:
- Toggle display of folder name/path along with the header info
- Include "In: [folder]" banner above message
  - Maybe only when viewed from search results?
- New message view menu option: Go to folder

I don't think the account needs to be listed since it can be deduced by the colored sidebar.

**Comment by cketti** [comment]
The folder name is now displayed in the message details screen. See #6647
